version: "3"

services:
  neo4j:
    image: neo4j:3.5.16
    container_name: neo4j
    volumes:
      - /opt/neo4j/data:/data
    environment:
    -  NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
    networks:
    - local
  nginx:
    image: nginx:1.14
    container_name: nginx
    networks:
    - local
    ports:
    - "80:80"
    - "443:443"
    - "7687:7687"
    - "7688:7688"
    volumes:
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    - ./nginx/ssl:/etc/nginx/conf.d/ssl

networks:
  local:
